env:
  es2021: true
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/no-non-null-assertion': error
  prettier/prettier: error
  require-jsdoc: error
  complexity:
    - warn
    - 10
  consistent-return: error
  camelcase: error

  yoda:
    - error

  curly:
    - error
    - all
  dot-notation:
    - error
    - allowKeywords: true
  # space-before-function-paren:
  #   - error
  #   - never
  padded-blocks:
    - error
    - never
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: false
  func-names: error

  max-len:
    - error
    - 79
  max-statements:
    - error
    - 100
  max-statements-per-line:
    - error
    - max: 1
  max-depth:
    - error
    - 5
  max-nested-callbacks:
    - error
    - 5

  eol-last:
    - error
    - always

  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0
      maxBOF: 0

  no-console: warn
  no-nested-ternary: warn

  no-empty-function: error
  no-floating-decimal: error
  no-inline-comments: error
  no-multi-spaces: error
  no-var: error
  no-eval: error
  no-lonely-if: error
  no-unneeded-ternary: error
  no-use-before-define: error
  no-trailing-spaces: error

  indent:
    - error
    - 4
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
